<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Nutrifami')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/circle.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>

    </head>

    <body ng-app="NutrifamiWeb">

    <ng-view>
        <?php echo $this->content; ?>
    </ng-view>
    <div id="audioS3"></div>
    <div id="imagenS3"></div>
    <!-- Scripts -->
    <?php
    echo $this->headScript()
            ->prependFile($this->basePath('js/nutrifami.js'))
            ->prependFile($this->basePath() . 'https://sdk.amazonaws.com/js/aws-sdk-2.3.15.min.js')
            ->prependFile($this->basePath('js/filters/filters.js'))
            ->prependFile($this->basePath('js/directives/narrador.drt.js'))
            ->prependFile($this->basePath('js/directives/goClick.drt.js'))
            ->prependFile($this->basePath('js/directives/leccionInfo.drt.js'))
            ->prependFile($this->basePath('js/directives/moduloInfo.drt.js'))
            ->prependFile($this->basePath('js/modals/compras.modal.js'))
            ->prependFile($this->basePath('js/modals/tips.modal.js'))
            ->prependFile($this->basePath('js/modals/feedbackUnidad.modal.js'))
            ->prependFile($this->basePath('js/modals/registro.modal.js'))
            ->prependFile($this->basePath('js/modals/login.modal.js'))
            ->prependFile($this->basePath('js/services/tipsService.js'))
            ->prependFile($this->basePath('js/services/capacitacionService.js'))
            ->prependFile($this->basePath('js/services/comprasService.js'))
            ->prependFile($this->basePath('js/services/anchorSmootScrollService.js'))
            ->prependFile($this->basePath('js/services/AuthenticationService.js'))
            ->prependFile($this->basePath('js/services/perfilService.js'))
            ->prependFile($this->basePath('js/services/usuarioService.js'))
            ->prependFile($this->basePath('js/controllers/juegoController.js'))
            ->prependFile($this->basePath('js/controllers/tipsModulosController.js'))
            ->prependFile($this->basePath('js/controllers/tipsController.js'))
            ->prependFile($this->basePath('js/controllers/progresoController.js'))
            ->prependFile($this->basePath('js/controllers/comprasController.js'))
            ->prependFile($this->basePath('js/controllers/sobreController.js'))
            ->prependFile($this->basePath('js/controllers/landingController.js'))
            ->prependFile($this->basePath('js/controllers/template/headerController.js'))
            ->prependFile($this->basePath('js/controllers/leccionTerminadaController.js'))
            ->prependFile($this->basePath('js/controllers/unidadController.js'))
            ->prependFile($this->basePath('js/controllers/moduloController.js'))
            ->prependFile($this->basePath('js/controllers/loginController.js'))
            ->prependFile($this->basePath('js/controllers/editarPerfilController.js'))
            ->prependFile($this->basePath('js/controllers/perfilController.js'))
            ->prependFile($this->basePath('js/controllers/capacitacionController.js'))
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('lib/angular-socialshare/dist/angular-socialshare.min.js'))
            ->prependFile($this->basePath('lib/js-md5/src/md5.js'))
            ->prependFile($this->basePath('lib/angular-loading-overlay/dist/angular-loading-overlay.js'))
            ->prependFile($this->basePath('lib/angular-bootstrap/ui-bootstrap-tpls.min.js'))
            ->prependFile($this->basePath('lib/angular-bootstrap/ui-bootstrap.min.js'))
            ->prependFile($this->basePath('lib/jquery/dist/jquery.min.js'))
            ->prependFile($this->basePath('lib/angular-animate/angular-animate.min.js'))
            ->prependFile($this->basePath('lib/angular-audio/app/angular.audio.js'))
            ->prependFile($this->basePath('lib/angular-cookies/angular-cookies.js'))
            ->prependFile($this->basePath('lib/angular-route/angular-route.js'))
            ->prependFile($this->basePath('lib/angular/angular.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'));
    ?>
</body>
</html>