<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Nutrifami')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        $version = '2.0.8';

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css?' . $version))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css?' . $version))
                ->prependStylesheet($this->basePath('lib/bootstrap/dist/css/bootstrap.css?' . $version))
                ->prependStylesheet($this->basePath('lib/angular-bootstrap/ui-bootstrap-csp.css?' . $version))
        ?>

        <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>

    </head>

    <body ng-app="nfweb">
    <ui-view>
        <?php echo $this->content; ?>
    </ui-view>
    <!-- Scripts -->
    <?php
    echo $this->headScript()
            ->prependFile($this->basePath() . 'https://sdk.amazonaws.com/js/aws-sdk-2.3.15.min.js')
            ->prependFile($this->basePath('lib/bootstrap/dist/js/bootstrap.min.js?' . $version))
            ->prependFile($this->basePath('services/anchorSmootScrollService.js?' . $version))
            ->prependFile($this->basePath('directives/language/language.drt.js?' . $version))
            ->prependFile($this->basePath('src/landing/landing.js?' . $version))
            ->prependFile($this->basePath('js/app.js?' . $version))
            ->prependFile($this->basePath('lib/jquery/dist/jquery.js?' . $version))
            ->prependFile($this->basePath('lib/angular-sanitize/angular-sanitize.min.js?' . $version))
            ->prependFile($this->basePath('lib/angular-cookies/angular-cookies.min.js?' . $version))
            ->prependFile($this->basePath('lib/angular-translate-loader-static-files/angular-translate-loader-static-files.js?' . $version))
            ->prependFile($this->basePath('lib/angular-translate-storage-cookie/angular-translate-storage-cookie.js?' . $version))
            ->prependFile($this->basePath('lib/angular-translate-storage-local/angular-translate-storage-local.js?' . $version))
            ->prependFile($this->basePath('lib/angular-translate-handler-log/angular-translate-handler-log.js?' . $version))
            ->prependFile($this->basePath('lib/angular-translate/angular-translate.js?' . $version))
            ->prependFile($this->basePath('lib/angular-bootstrap/ui-bootstrap-tpls.js?' . $version))
            ->prependFile($this->basePath('lib/angular-bootstrap/ui-bootstrap.js?' . $version))
            ->prependFile($this->basePath('lib/angular-touch/angular-touch.js?' . $version))
            ->prependFile($this->basePath('lib/angular-animate/angular-animate.js?' . $version))
            ->prependFile($this->basePath('lib/angular-ui-router/release/angular-ui-router.js?' . $version))
            ->prependFile($this->basePath('lib/angular/angular.js?' . $version))
    ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {

                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)

        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-88108666-1', 'auto');
        ga('send', 'pageview');
    </script>
</body>
</html>